# Generated by Django 5.0.6 on 2024-06-15 00:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_task_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='description',
            new_name='task_description',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='name',
            new_name='task_name',
        ),
    ]
