# Generated by Django 5.0.6 on 2024-06-15 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_task_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.IntegerField(choices=[(1, 'Baixa'), (2, 'Média'), (3, 'Alta')]),
        ),
    ]
