# Generated by Django 5.0.6 on 2024-06-19 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_task_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='address',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='category',
            field=models.CharField(choices=[('Limpeza', 'Limpeza'), ('Conserto', 'Conserto'), ('Recreação', 'Recreação'), ('Segurança', 'Segurança')], default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='task',
            name='problem_photo',
            field=models.ImageField(blank=True, null=True, upload_to='problems/'),
        ),
        migrations.AddField(
            model_name='task',
            name='solution_photo',
            field=models.ImageField(blank=True, null=True, upload_to='solutions/'),
        ),
    ]
