# Generated by Django 5.0.6 on 2024-06-19 18:57

from django.db import migrations, models, connection


def add_columns(apps, schema_editor):
    with connection.cursor() as cursor:
        cursor.execute("SELECT column_name FROM information_schema.columns WHERE table_name='core_task'")
        existing_columns = [row[0] for row in cursor.fetchall()]
        
        if 'address' not in existing_columns:
            schema_editor.execute("ALTER TABLE core_task ADD COLUMN address VARCHAR(255)")
        
        if 'category' not in existing_columns:
            schema_editor.execute("ALTER TABLE core_task ADD COLUMN category VARCHAR(50)")
        
        if 'completed' not in existing_columns:
            schema_editor.execute("ALTER TABLE core_task ADD COLUMN completed BOOLEAN DEFAULT FALSE")
        
        if 'problem_photo' not in existing_columns:
            schema_editor.execute("ALTER TABLE core_task ADD COLUMN problem_photo VARCHAR(100)")
        
        if 'solution_photo' not in existing_columns:
            schema_editor.execute("ALTER TABLE core_task ADD COLUMN solution_photo VARCHAR(100)")



class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_task_priority'),
    ]

    operations = [
        migrations.RunPython(add_columns),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='category',
            field=models.CharField(choices=[('Limpeza', 'Limpeza'), ('Conserto', 'Conserto'), ('Recreação', 'Recreação'), ('Segurança', 'Segurança')], default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='problem_photo',
            field=models.ImageField(blank=True, null=True, upload_to='problems/'),
        ),
        migrations.AddField(
            model_name='task',
            name='solution_photo',
            field=models.ImageField(blank=True, null=True, upload_to='solutions/'),
        ),
    ]
