# Generated by Django 5.0 on 2024-06-21 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_task_address_task_category_task_completed_and_more'),
        ('core', '0010_task_address_task_completed'),
    ]

    operations = [
    ]
